### ISSUE TITLE
scoreCooksDistance uses default predict function

### ISSUE THREAD

**Issue by maksymiuks** [MI2DataLab/auditor#107]
as in the title, scoreCooksDistance uses default predict and therefore rises errors when trying to use various models

**Comment by agosiewska** [comment]
I don;t understand, for me it looks like 'score_cooksdistance' uses predict function from explainer

https://github.com/MI2DataLab/auditor/blob/74905f2b0251d1a97bee61a8423f55cbbc804893/R/score_cooksdistance.R#L52-L68

**Comment by maksymiuks** [comment]
Now yes, It wasn't on the previous master branch. Also, now argument `newdata` is missig in 58th line of your code and it throws an error.

**Comment by agosiewska** [comment]
Thank you :)
I have fixed this, please, check if it works for you now.

**Comment by maksymiuks** [comment]
First of all, thank You for help and, I would like to express my appreciation of Your hard work under auditor project.

Unfortunatelly function is still not working. Now problem exists in line 63. Models that have been built  for instance with mlr-gbm or scikit-learn cannot be target of update function and that line throws an error.

**Comment by agosiewska** [comment]
funny.
I know, this will work only for models with the update method.

**Comment by agosiewska** [comment]
I have added information in the documentation

**Comment by maksymiuks** [comment]
Thanks :)
